#!/usr/bin/env bash

NO_FORMAT="\033[0m"
C_RED="\033[38;5;9m"
F_BOLD="\033[1m"

[[ $1 == '-stub' ]] \
    && stub='-stub' \
    || stub=''

[[ $1 == '-stub' ]] \
    && echo 'Executing with -stub' \
    || echo -e "${C_RED}${F_BOLD}Executing without -stub${NO_FORMAT}"

nextflow run \
    main.nf \
    -profile docker,test_full \
    -resume \
    $stub \
    -c ../nxf-config/resources.config \
    --eggnogmapper_db_dir ../dbs/emapperdb/5.0.2 \
    --outdir results
